lib/da_funk/payment_channel.rb

Using payment channel interface

Added support to get http code status

---

lib/da_funk/application.rb
lib/da_funk/screen.rb
lib/device/runtime.rb

Now after an application download, the old application cached in memory is removed from the instance list and re load it's newest version.

Added cache mechanism after download

---

lib/da_funk/version.rb
lib/iso8583/field.rb

- Fix method call
- Version bump

Fix version

---

lib/da_funk/helper.rb

Error found on methods added to touch screen operations (Helper)

Bug fix local jump error: unexpected return

---

Gemfile
Gemfile.lock
lib/da_funk/helper.rb

- Library to be used when developing unit or integration tests.

Add funky mock library

---

lib/da_funk/helper.rb

Now it will return nil if key pressed is CANCEL.

Changed Dafunk::Helper#menu return

---

RELEASE_NOTES.md
lib/da_funk/helper.rb

Added beep responsible to da_funk, also removed from mruby-pax gem.

Fix touchscreen beep

---

lib/device/setting.rb

- Just changed a config.dat variable name.

Changed emv setting emv_input_amount_idle to emv_contactless_amount

---

lib/device/setting.rb

- Added support to cloudwalk and google endpoint on infinitepay config settings

Added support to infinitepay dns config.

---

lib/da_funk/helper.rb
lib/da_funk/params_dat.rb

- DaFunk::ParamsDat#download
- DaFunk::ParamsDat#update_apps
- DaFunk::ParamsDat#update_app
- DaFunk::ParamsDat#update_file
- DaFunk::Helper#attach_options
- DaFunk::Helper#check_download_error
This parameters will say if it's necessary to print text on these
methods.

Added enable_txt_ui parameter on the following methods

---

lib/da_funk/helper.rb

If :special_keys Array include this key.

On DaFunk::Helper#menu_image_touchscreen_or_keyboard return key

---

lib/da_funk/helper/status_bar.rb

Support to new status bar which includes:
- Battery percentage represented also in numbers;
- Battery level;
- Media (WIFI or GPRS);
- Media signal strength;

Status bar improments

---

lib/device/virtual_keyboard.rb

- I have made some adjustments to work with while instead loop statement
- Added wifi_password method to indicates that it will capture password

Virtual keyboard adjustment

---

Rakefile
lib/da_funk/params_dat.rb
lib/device/signature.rb
test/unit/device/signature_test.rb

With this mod we will be able to update `device.sig` file with whatever value we want after updating params.dat file

Support signature conversion

---

lib/da_funk/helper/status_bar.rb

We will be able to print a message "Buscando" and "Conectado" on status bar

Added support to network state on status bar

---

lib/device/virtual_keyboard.rb

Added support to physical number keys on virtual keyboard.

Add support to physical number keys on virtual keyboard

---

lib/da_funk/params_dat.rb
lib/device/setting.rb

- Support of params.dat restore if it's corrupted

Params dat persistence

---

Rakefile
lib/da_funk/secure_random.rb
test/unit/da_funk/secure_random.rb

- Added support to ruby SecureRandom

Addes support to SecureRandom

---

Rakefile
lib/da_funk/helper/status_bar.rb
lib/da_funk/transaction/reversal.rb
lib/device/display.rb

- Added support to new image with notification
- Replace GPRS to 3G icon on status bar
- Added new DaFunk:: Transaction:: Reversal class in order to check if reversal file exists

Reversal improvements

---

lib/da_funk/helper.rb
lib/da_funk/params_dat.rb

- Support to images on DaFunk::ParamDat#Download

Params dat download improvements
